"""empty message

Revision ID: 1651d570ebf3
Revises: 65e5c83c170
Create Date: 2015-12-23 21:35:55.898068

"""

# revision identifiers, used by Alembic.
revision = '1651d570ebf3'
down_revision = '65e5c83c170'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
