"""empty message

Revision ID: 2f2d7a5a6ff8
Revises: 3f13f55d1da
Create Date: 2015-07-18 21:12:58.002568

"""

# revision identifiers, used by Alembic.
revision = '2f2d7a5a6ff8'
down_revision = '3f13f55d1da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
