"""empty message

Revision ID: 31f83f4ddcb6
Revises: ad608cafb79
Create Date: 2015-05-14 16:03:56.002396

"""

# revision identifiers, used by Alembic.
revision = '31f83f4ddcb6'
down_revision = 'ad608cafb79'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'posts_author_id_fkey', 'posts', type_='foreignkey')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(u'posts_author_id_fkey', 'posts', 'users', ['author_id'], ['id'])
    ### end Alembic commands ###
