"""empty message

Revision ID: 3d3bbaa94963
Revises: 543a3bcb0e4e
Create Date: 2015-06-28 11:47:46.718066

"""

# revision identifiers, used by Alembic.
revision = '3d3bbaa94963'
down_revision = '543a3bcb0e4e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_id_auto', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('author_id_manual', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('creation_date', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('image_link', sa.String(), nullable=True))
    op.drop_constraint(u'posts_author_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author_id_auto'], ['id'])
    op.drop_column('posts', 'author_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(u'posts_author_id_fkey', 'posts', 'users', ['author_id'], ['id'])
    op.drop_column('posts', 'image_link')
    op.drop_column('posts', 'creation_date')
    op.drop_column('posts', 'author_id_manual')
    op.drop_column('posts', 'author_id_auto')
    ### end Alembic commands ###
