"""empty message

Revision ID: 518d0f751769
Revises: 31f83f4ddcb6
Create Date: 2015-05-14 16:04:49.390947

"""

# revision identifiers, used by Alembic.
revision = '518d0f751769'
down_revision = '31f83f4ddcb6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    ### end Alembic commands ###
