"""empty message

Revision ID: 543a3bcb0e4e
Revises: None
Create Date: 2015-06-25 14:37:27.291548

"""

# revision identifiers, used by Alembic.
revision = '543a3bcb0e4e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
