"""empty message

Revision ID: 58d165631186
Revises: 2f2d7a5a6ff8
Create Date: 2015-10-01 00:14:40.845839

"""

# revision identifiers, used by Alembic.
revision = '58d165631186'
down_revision = '2f2d7a5a6ff8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
