"""empty message

Revision ID: 65e5c83c170
Revises: 58d165631186
Create Date: 2015-10-01 00:23:14.011648

"""

# revision identifiers, used by Alembic.
revision = '65e5c83c170'
down_revision = '58d165631186'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
