"""empty message

Revision ID: a3b5f3ccada
Revises: None
Create Date: 2015-06-25 14:16:41.028700

"""

# revision identifiers, used by Alembic.
revision = 'a3b5f3ccada'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
