"""empty message

Revision ID: ad608cafb79
Revises: 2b8d8358dfb9
Create Date: 2015-05-14 15:45:45.465766

"""

# revision identifiers, used by Alembic.
revision = 'ad608cafb79'
down_revision = '2b8d8358dfb9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
